# Generated by Django 4.0.2 on 2022-03-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'db_cate',
            },
        ),
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('host_flag', models.IntegerField()),
            ],
            options={
                'db_table': 'db_cust',
            },
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=20)),
                ('reg_num', models.CharField(max_length=10, unique=True)),
                ('host_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('openhour', models.CharField(blank=True, max_length=100, null=True)),
                ('breakhour', models.CharField(blank=True, max_length=100, null=True)),
                ('restimg', models.CharField(blank=True, max_length=100, null=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cate')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cust')),
            ],
            options={
                'db_table': 'db_rest',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('regdate', models.DateField(auto_now=True)),
                ('s_rating', models.IntegerField()),
                ('m_rating', models.IntegerField()),
                ('p_rating', models.IntegerField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cust')),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rest')),
            ],
            options={
                'db_table': 'db_review',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('menuimg', models.CharField(blank=True, max_length=100, null=True)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rest')),
            ],
            options={
                'db_table': 'db_menu',
            },
        ),
        migrations.CreateModel(
            name='Imgpath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.review')),
            ],
            options={
                'db_table': 'db_imgpath',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cust')),
            ],
            options={
                'db_table': 'db_board',
            },
        ),
    ]
